### ISSUE TITLE
nacos lib crash

### ISSUE THREAD

**Issue by yyzhang123** [nacos-group/nacos-sdk-cpp#79] opened 2021-07-06 07:22 UTC
When the Nacos client uses UDP_ RECEIVER_PORT option sets the listening port and the port is occupied, the Nacos library will crashes.  The stack is shown as follows:  

#0  0x00007f703123a387 in raise () from /usr/lib64/libc.so.6
#1  0x00007f703123ba78 in abort () from /usr/lib64/libc.so.6
#2  0x0000000000782fa1 in nacos::Thread::threadFunc (param=0x1c0e910) at ./src/thread/Thread.cpp:33
#3  0x00007f7031dfbea5 in start_thread () from /usr/lib64/libpthread.so.0
#4  0x00007f70313029fd in clone () from /usr/lib64/libc.so.6

===================================================
I found that the logs in Nacos local directory are as follows:
[2021-07-06 14:53:15]Exception happens when executing:
[2021-07-06 14:53:15]Thread Name:configUDPListener Thread Id:45908
[2021-07-06 14:53:15]Raison:Unable to bind

I found that the source code threw an exception in udpnamingservicelistener:: initializeudplistener()， But there is no try catch where it is called, so the listener thread exits。 I suggest adding try catch outside the place where initializeUdpListener is called in function UdpNamingServiceListener:: listenerThreadFunc (void *param) to catch the exception so that the program will not crash.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment] 2021-07-09 16:36
This crash is on purpose, since the port it tries to bind is already occupied:
[2021-07-06 14:53:15]Exception happens when executing:
[2021-07-06 14:53:15]Thread Name:configUDPListener Thread Id:45908
[2021-07-06 14:53:15]**_Raison:Unable to bind_**

**Comment by yyzhang123** [comment] 2021-07-12 01:56
Will the main program crash if the port is occupied? Why? Why can't I fail to call the initialization function and return?

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment] 2021-07-15 12:59
Hi @yyzhang123 
Usually this is caused by a configuration failure, which can not be resolved by the program itself, so it would be better to let the program crash and fix the configuration manually.

**Closed by TTTTTAAAAAKKKKEEEENNNN** 2021-07-15 12:59 UTC
