### ISSUE TITLE
it throws exception when getinstance if instanceId is null

### ISSUE THREAD

**Issue by keranbingaa** [nacos-group/nacos-sdk-cpp#70] opened 2021-05-26 02:22 UTC
java sdk updated with nacos 2.x,and when register instance with java sdk, the instanceId is null.it will throw exception if we query instance which registered by java sdk. Maybe we also need to consider this problem in c++ sdk.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment] 2021-05-26 15:49
We're now discussing with Nacos developer to confirm whether this is an issue or a design.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment] 2021-06-05 01:27
I've checked with the PMC and confirmed that this is a feature change in Nacos 2.0, the InstanceId is no longer generated on the server side. We will generate the Id on the client side and disable InstanceId check to fix this issue

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment] 2021-06-07 15:13
Could you check if the issue is resolved with the develop branch?
https://github.com/nacos-group/nacos-sdk-cpp/tree/develop

If so, please kindly close this issue :)

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment] 2021-06-12 13:41
I'm closing this issue since I didn't get any response.
Should you have any further question, please re-open this issue

**Closed by TTTTTAAAAAKKKKEEEENNNN** 2021-06-12 13:41 UTC
